packages:
  - "apps/*"
  - "packages/*"
  - "configs/*"

catalog:
  # typescript
  "typescript": "5.8.2"
  "tsup": "8.1.0"
  "vite": "5.3.4"
  "vitest": "2.1.5"
  "vite-tsconfig-paths": "4.3.2"
  "happy-dom": "14.12.0"
  "vitest-fetch-mock": "0.2.2"  
  "@testing-library/jest-dom": "6.4.5"
  "@testing-library/react": "16.0.0"
  "@testing-library/user-event": "14.5.2"
  "@vitejs/plugin-react": "4.3.1"
  "@vitest/coverage-v8": "2.1.5"

  "next": "^15.0.3"
  "sharp": "^0.33.5"

  # tailwindcss
  "autoprefixer": "^10.4.20"
  "postcss": "^8.4.47"
  "tailwindcss": "^3.4.14"
  "clsx": "^2.1.1"
  "class-variance-authority": "^0.7.0"

  "es-toolkit": "^1.27.0"
  "overlay-kit": "^1.4.1"
  "@suspensive/react": "^2.18.5"
  "@hookform/resolvers": "^3.9.1"
  "zod": "^3.23.8"
  "react-hook-form": "^7.53.2"
  "@types/node": "^20"

catalogs:
  react18:
    "react": "^18.3.1"
    "react-dom": "^18.3.1"
    "@types/react": "^18.3.12"
    "@types/react-dom": "^18.3.1"
    "react-native": "^0.76.1"

  react19:
    "react": "^19.0.0-rc-66855b96-20241106"
    "react-dom": "^19.0.0-rc-66855b96-20241106"
    "@types/react": "^18.3.12"
    "@types/react-dom": "^18.3.1"

  react-query5:
    "@tanstack/react-query": "^5.59.16"
    "@tanstack/react-query-devtools": "^5.59.16"
    "@tanstack/react-query-next-experimental": "^5.59.16"
