packages:
  - "apps/*"
  - "packages/*"
  - "configs/*"

catalog:
  # typescript
  "typescript": "5.8.3"
  "tsup": "8.4.0"
  "vite": "6.2.6"
  "vitest": "3.1.1"
  "vite-tsconfig-paths": "5.1.4"
  "happy-dom": "17.4.4"
  "vitest-fetch-mock": "0.2.2"  
  "@testing-library/jest-dom": "6.6.3"
  "@testing-library/react": "16.3.0"
  "@testing-library/user-event": "14.6.1"
  "@vitejs/plugin-react": "4.3.4"
  "@vitest/coverage-v8": "3.1.1"

  "next": "^15.3.0"
  "sharp": "^0.34.1"

  # tailwindcss
  "autoprefixer": "^10.4.20"
  "postcss": "^8.4.47"
  "tailwindcss": "^3.4.14"
  "clsx": "^2.1.1"
  "class-variance-authority": "^0.7.0"

  "es-toolkit": "^1.34.1"
  "overlay-kit": "^1.7.0"
  "@suspensive/react": "^2.18.12"
  "@hookform/resolvers": "^3.9.1"
  "zod": "^3.23.8"
  "react-hook-form": "^7.53.2"
  "@types/node": "^20"

catalogs:
  react18:
    "react": "^18.3.1"
    "react-dom": "^18.3.1"
    "@types/react": "^18.3.12"
    "@types/react-dom": "^18.3.1"
    "react-native": "^0.76.1"

  react19:
    "react": "^19.1.0"
    "react-dom": "^19.1.0"
    "@types/react": "^18.3.12"
    "@types/react-dom": "^18.3.1"

  react-query5:
    "@tanstack/react-query": "^5.72.2"
    "@tanstack/react-query-devtools": "^5.72.2"
    "@tanstack/react-query-next-experimental": "^5.72.2"
