import { VariantProps, cva } from "class-variance-authority";
import { ResponsiveEnumProps } from "./type";

export type TextSizeTypeProps = { size?: ResponsiveEnumProps<VariantProps<typeof textSizeVariants>["initial"]> };
export const textSizeVariants = cva("", {
  variants: {
    initial: {
      "12": "text-size-12",
      "11": "text-size-11",
      "10": "text-size-10",
      "9": "text-size-9",
      "8": "text-size-8",
      "7": "text-size-7",
      "6": "text-size-6",
      "5": "text-size-5",
      "4": "text-size-4",
      "3": "text-size-3",
      "2": "text-size-2",
      "1": "text-size-1",
    },
    xs: {
      "12": "xs:text-size-12",
      "11": "xs:text-size-11",
      "10": "xs:text-size-10",
      "9": "xs:text-size-9",
      "8": "xs:text-size-8",
      "7": "xs:text-size-7",
      "6": "xs:text-size-6",
      "5": "xs:text-size-5",
      "4": "xs:text-size-4",
      "3": "xs:text-size-3",
      "2": "xs:text-size-2",
      "1": "xs:text-size-1",
    },
    md: {
      "12": "md:text-size-12",
      "11": "md:text-size-11",
      "10": "md:text-size-10",
      "9": "md:text-size-9",
      "8": "md:text-size-8",
      "7": "md:text-size-7",
      "6": "md:text-size-6",
      "5": "md:text-size-5",
      "4": "md:text-size-4",
      "3": "md:text-size-3",
      "2": "md:text-size-2",
      "1": "md:text-size-1",
    },
    xl: {
      "12": "xl:text-size-12",
      "11": "xl:text-size-11",
      "10": "xl:text-size-10",
      "9": "xl:text-size-9",
      "8": "xl:text-size-8",
      "7": "xl:text-size-7",
      "6": "xl:text-size-6",
      "5": "xl:text-size-5",
      "4": "xl:text-size-4",
      "3": "xl:text-size-3",
      "2": "xl:text-size-2",
      "1": "xl:text-size-1",
    },
  },
});
